# Generated by Django 3.0.5 on 2020-04-13 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
